# Generated by Django 4.2.2 on 2023-07-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_acerca_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icono',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Icono'),
        ),
    ]
